/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dark;

import static dark.Dark.ventanaInicio;
import javax.swing.JComboBox;

/**
 *
 * @author manueljesusgarcialopez
 */
public class Ordenes extends javax.swing.JPanel {

    
    
    /**
     * Creates new form Ordenes
     */
    public Ordenes() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonOrdenar1 = new javax.swing.JButton();
        jButtonCancelar1 = new javax.swing.JButton();
        jComboBox1_1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButtonOrdenar2 = new javax.swing.JButton();
        jButtonCancelar2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButtonOrdenar3 = new javax.swing.JButton();
        jButtonCancelar3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setForeground(new java.awt.Color(102, 0, 255));
        setPreferredSize(new java.awt.Dimension(400, 234));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), new java.awt.Color(153, 153, 0)));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setAlignmentX(1.0F);
        jTabbedPane1.setAlignmentY(1.0F);
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(400, 234));

        jLabel1.setText("Acción:");

        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("          ");

        jButtonOrdenar1.setText("Ordenar");
        jButtonOrdenar1.setEnabled(false);
        jButtonOrdenar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenar1ActionPerformed(evt);
            }
        });

        jButtonCancelar1.setText("Cancelar");
        jButtonCancelar1.setEnabled(false);
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });

        jComboBox1_1.setEnabled(false);
        jComboBox1_1.setMinimumSize(new java.awt.Dimension(100, 27));
        jComboBox1_1.setSize(new java.awt.Dimension(200, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenar1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, 284, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonOrdenar1)
                        .addComponent(jButtonCancelar1))))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jLabel1");

        jTabbedPane1.addTab("Acción 1", jPanel2);

        jLabel2.setText("Acción:");

        jComboBox2.setEnabled(false);

        jLabel6.setText("          ");

        jButtonOrdenar2.setText("Ordenar");
        jButtonOrdenar2.setEnabled(false);
        jButtonOrdenar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenar2ActionPerformed(evt);
            }
        });

        jButtonCancelar2.setText("Cancelar");
        jButtonCancelar2.setEnabled(false);
        jButtonCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenar2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonOrdenar2)
                        .addComponent(jButtonCancelar2))))
        );

        jLabel2.getAccessibleContext().setAccessibleName("jLabel2");

        jTabbedPane1.addTab("Acción 2", jPanel3);

        jLabel3.setText("Acción:");

        jComboBox3.setEnabled(false);

        jLabel7.setText("          ");

        jButtonOrdenar3.setText("Ordenar");
        jButtonOrdenar3.setEnabled(false);
        jButtonOrdenar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenar3ActionPerformed(evt);
            }
        });

        jButtonCancelar3.setText("Cancelar");
        jButtonCancelar3.setEnabled(false);
        jButtonCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, 0, 284, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenar3)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonOrdenar3)
                        .addComponent(jButtonCancelar3))))
        );

        jTabbedPane1.addTab("Acción 3", jPanel4);

        jLabel4.setText("          ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 321, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 154, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jTabbedPane1.addTab("Información", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
        
      
    private void jButtonOrdenar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenar2ActionPerformed
        //desactivamos la acción, se queda como marcada...
        jComboBox2.setEnabled(false);
        //Guardamos la acción seleccionada en el combobox
        int idAccion = Dark.ventanaInicio.ordenes.jComboBox2.getSelectedIndex();
        //Guardamos la acción en el ArrayList de las acciones
        int posicion = Dark.ventanaInicio.PJ;
        System.out.println("Posicion para List: " + posicion);
        //Guardamos la orden
        EnviarOrdenes orden2; //Creamos una instancia
        //Recuperamos los valores de las ordenes de ese PJ
        orden2 = Dark.ventanaInicio.ordenesPJ.get(posicion);
        //Asignamos el nuevo valor de la accion selecciona en el objeto
        orden2.accion2 = idAccion;
        System.out.println("Orden para List: " + orden2.accion2);
        //Almacenamos el objeto en el ArrayList
        Dark.ventanaInicio.ordenesPJ.set(posicion, orden2);
        //Ponemos los botones en orden
        jButtonOrdenar2.setEnabled(false);
        jButtonCancelar2.setEnabled(true);
    }//GEN-LAST:event_jButtonOrdenar2ActionPerformed

    private void jButtonOrdenar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenar3ActionPerformed
        //desactivamos la acción, se queda como marcada...
        jComboBox3.setEnabled(false);
        //Guardamos la acción seleccionada en el combobox
        int idAccion = Dark.ventanaInicio.ordenes.jComboBox3.getSelectedIndex();
        //Guardamos la acción en el ArrayList de las acciones
        int posicion = Dark.ventanaInicio.PJ;
        System.out.println("Posicion para List: " + posicion);
        //Guardamos la orden
        EnviarOrdenes orden3; //Creamos una instancia
        //Recuperamos los valores de las ordenes de ese PJ
        orden3 = Dark.ventanaInicio.ordenesPJ.get(posicion);
        //Asignamos el nuevo valor de la accion selecciona en el objeto
        orden3.accion3 = idAccion;
        System.out.println("Orden para List: " + orden3.accion3);
        //Almacenamos el objeto en el ArrayList
        Dark.ventanaInicio.ordenesPJ.set(posicion, orden3);
        //Ponemos los botones en orden
        jButtonOrdenar3.setEnabled(false);
        jButtonCancelar3.setEnabled(true);
    }//GEN-LAST:event_jButtonOrdenar3ActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        //desactivamos la acción, se queda como marcada...
        jComboBox1.setEnabled(true);
        //Ponemos los botones en orden
        jButtonOrdenar1.setEnabled(true);
        jButtonCancelar1.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void jButtonCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar2ActionPerformed
        //desactivamos la acción, se queda como marcada...
        jComboBox2.setEnabled(true);
        //Ponemos los botones en orden
        jButtonOrdenar2.setEnabled(true);
        jButtonCancelar2.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelar2ActionPerformed

    private void jButtonCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar3ActionPerformed
        //desactivamos la acción, se queda como marcada...
        jComboBox3.setEnabled(true);
        //Ponemos los botones en orden
        jButtonOrdenar3.setEnabled(true);
        jButtonCancelar3.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelar3ActionPerformed

    private void jButtonOrdenar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenar1ActionPerformed
        //desactivamos la acción, se queda como marcada...
        jComboBox1.setEnabled(false);
        //Guardamos la acción seleccionada en el combobox
        int idAccion = Dark.ventanaInicio.ordenes.jComboBox1.getSelectedIndex();
        //Guardamos la acción en el ArrayList de las acciones
        int posicion = Dark.ventanaInicio.PJ;
        System.out.println("Posicion para List: " + posicion);
        //Guardamos la orden
        EnviarOrdenes orden1; //Creamos una instancia
        //Recuperamos los valores de las ordenes de ese PJ
        orden1 = Dark.ventanaInicio.ordenesPJ.get(posicion);
        //Asignamos el nuevo valor de la accion selecciona en el objeto
        orden1.accion1 = idAccion;
        System.out.println("Orden para List: " + orden1.accion1);
        //Almacenamos el objeto en el ArrayList
        Dark.ventanaInicio.ordenesPJ.set(posicion, orden1);
        //Ponemos los botones en orden
        jButtonOrdenar1.setEnabled(false);
        jButtonCancelar1.setEnabled(true);
    }//GEN-LAST:event_jButtonOrdenar1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //Preguntamos por la acción seleccionada para actuar en consecuencia
        if(jComboBox1.getSelectedIndex() == 0) {
            ventanaInicio.ordenes.jComboBox1_1.setVisible(true);
            ventanaInicio.ordenes.jComboBox1_1.setEnabled(true);
            cargarMenuEscogerLugar();
        } else {
            //ventanaInicio.ordenes.jComboBox1_1.setVisible(false);
            //ventanaInicio.ordenes.jComboBox1_1.setEnabled(false);
            cargarMenuEscogerEnemigo();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCancelar1;
    public javax.swing.JButton jButtonCancelar2;
    public javax.swing.JButton jButtonCancelar3;
    public javax.swing.JButton jButtonOrdenar1;
    public javax.swing.JButton jButtonOrdenar2;
    public javax.swing.JButton jButtonOrdenar3;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox1_1;
    public javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JComboBox<String> jComboBox3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    //Método que carga los comboBox de las órdenes o acciones del juego
    public void cargarMenu() {
        
        //System.out.println("CC:" + ventanaInicio.jTable5.getComponentCount());
        //Vemos el numero de componentes de las acciones
        int n_acciones = ventanaInicio.jTable5.getRowCount();
        try {
            
            //Cargamos los combos de las acciones de los PJs
            System.out.println("COMPOS: " + ventanaInicio.jTable5.getValueAt(1, 2));
            for(int x=0; x<n_acciones;x++) {
                jComboBox1.addItem((String) ventanaInicio.jTable5.getValueAt(x, 1));
                jComboBox2.addItem((String) ventanaInicio.jTable5.getValueAt(x, 1));
                jComboBox3.addItem((String) ventanaInicio.jTable5.getValueAt(x, 1));
            }
        } catch (NullPointerException ex) {
            System.out.println("Esta excepcion: " + ex.getMessage() + ex.getLocalizedMessage());
        }
    }
    public void cargarMenuEscogerLugar() {
        //Posiciones del PJ escogido (Imaginaria... hay que calcularla)
        int posPJx = 10;
        int posPJy = 6;
        //Eliminamos los datos anteriores
        jComboBox1_1.removeAllItems();
        //jComboBoxElegirCoor.setLocation(new java.awt.Point(150, 80));
        try {
            //Cargamos el combo con las casillas a las que puede acceder el PJ
            for(int x=posPJx-3; x<posPJx+4;x++) {
                for(int y=posPJy-3; y<posPJy+4;y++) {
                    jComboBox1_1.addItem((String) (x + "-" + y));
                }
            }
        } catch (NullPointerException ex) {
            
        }
    }
    
    public void cargarMenuEscogerEnemigo() {
        //Creamos el String con los Bandos que se cargarán de la BBDD
        String[] bandos;
        try {
            //Abrimos la conexion con la BBDD
            Dark.con.connect();
            //Cargamos los datos
            bandos = Dark.con.cargarBandos();
            //Eliminamos los datos anteriores
            jComboBox1_1.removeAllItems();
            //Cargamos el comboBox con el array de los bandos
            for(int x=0; x<bandos.length;x++) {
                jComboBox1_1.addItem(bandos[x]);
            }
            //Cerramos la conexion
            Dark.con.close();
        } catch (NullPointerException ex) {
            
        }
    }

}

